id: A984444B4
base_file: f214F.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 13:58:05.731668
  last_modified_at: 2022-06-17 13:58:05.731681
