id: A984444B4
base_file: f44A0.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 13:58:05.741225
  last_modified_at: 2022-06-17 13:58:05.741232
