id: A984444B4
base_file: f2948.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 13:58:05.734929
  last_modified_at: 2022-06-17 13:58:05.734935
