id: A984444B4
base_file: fFB2E.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 13:58:05.751785
  last_modified_at: 2022-06-17 13:58:05.751790
