id: A984444B4
base_file: fD25B.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 13:58:05.748411
  last_modified_at: 2022-06-17 13:58:05.748416
